### ISSUE TITLE
Draw square boxes around automatically parsed Python types instead of pure HTML links

### ISSUE THREAD

**Issue by 1kastner** [sphinx-doc/sphinx#10776]
**Is your feature request related to a problem? Please describe.**
There is no real problem, rather aesthetics.

**Describe the solution you'd like**
I would like to have a box around the Python types instead of a default HTML link. I like the following appearance:

![grafik](https://user-images.githubusercontent.com/5236165/185383575-0731fda4-8cf3-4c87-80d5-1c3538539158.png)

However, when I describe my keyword arguments, default HTML links are used:

![grafik](https://user-images.githubusercontent.com/5236165/185383923-c3e374bb-5dbd-42aa-9682-65663f324dc3.png)

I like the boxes more. What especially bugs me is that currently, several styles are used to represent the same concept. This is partly my fault because of the configuration I chose. When I tried to streamline the visual appearance, however, I realised that I have limited control over this. As this is about taste, I guess it is better to add another option to the config and leave it up to the maintainer of a documentation to choose between a pure html link and a pre-styled box.

**Describe alternatives you've considered**
While writing doc strings, I could use the [py obj role](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#role-py-obj) whenever encountering these types and do this job manually. That is some manual work and I would prefer if there was an automated way to solve this.

**Comment by 1kastner** [comment]
One thing I forgot to point out - there is no link pointing to typing.Optional! In the signature, however, everything is created as it should be.

**Comment by 1kastner** [comment]
A hacky interims solution is to style the links as if they were a pre class. This, however, is not very stable and it might introduce future problems. This leads to the intended visual appearance. However, it does not add the links for `Optional` that went missing. As mentioned above, in several cases I can fix that myself by using the py obj role. This is not true when the type hints are derived from the code and inheritance comes into play, see https://github.com/sphinx-doc/sphinx/issues/10793 for a slightly more detailed discussion.

```css
a.reference>em {
    box-sizing: border-box;
    font-family: SFMono-Regular,Menlo,Monaco,Consolas,Liberation Mono,Courier New,Courier,monospace;
    padding: 2px 5px;
    background: #fff;
    border: 1px solid #e1e4e5;
    font-size: 75%;
    font-style: normal;
    color: #404040;
    font-weight: 700;
}

a+em, em+em {
    font-style: normal;
}
```
