### ISSUE TITLE
Add a way to cross-reference code in prose text

### ISSUE THREAD

**Issue by cjdb** [sphinx-doc/sphinx#11430]
**Is your feature request related to a problem? Please describe.**
It's sometimes easier to refer to a part of an API by describing it, rather than by directly naming it, but the C++ cross-reference directives only render in monospace font.

For example:
```
and the type of ``x <=> y`` :cpp:type:`can be reduced to \`\`Cat\`\`.<std::common_comparison_category>`
```
will be rendered as
> and the type of `x <=> y` [```can be reduced to ``Cat``.```]()

**Describe the solution you'd like**
It should be possible to render the above as 

> and the type of `x <=> y` [can be reduced to ``Cat``.]()

I noticed that there's `:cpp:expr:` and `:cpp:texpr:`. Perhaps there should be a `t`-prefixed cross-reference for all of the API cross-references (e.g. `cpp:ttype`).

**Comment by jfbu** [comment]
Does using custom CSS styling help? I defined a file `_static/custom.css` with these contents
```css
code.cpp-type > .pre {
   font-style: normal;
   font-family: roman;
   font-weight: normal;
   /*text-decoration: underline*/
}
```
as a test and it appears to work (with default `html_static_path = ['_static']` in `conf.py`) (although the escaped `` ` `` will show literally)
