### ISSUE TITLE
Ability to repeat an admonition

### ISSUE THREAD

**Issue by LecrisUT** [sphinx-doc/sphinx#11807]
Let's consider that we have a similar `admonition` for warning, tldr, etc. that is repeated in multiple documents. It would be nice to have a simple way of just including the content from a centrally defined one, without using `include` directive

**Comment by SilverRainZ** [comment]
What's the problem with `include`?

**Comment by LecrisUT** [comment]
In this case, the indirectness. I would have to manage a separate file with some kind of tagging mechanism. And then there's the issue that `name` amd other indexing would not work because of its duplication

**Comment by electric-coder** [comment]
> It would be nice to have a simple way of just including the content from a centrally defined one, without using include directive

No it would not be nice! Because it would require adding a superfluous functionality with no concrete gains.

**Comment by LecrisUT** [comment]
@electric-coder I have spun up a MWE to show how the `name` directive can be problematic: https://github.com/LecrisUT/sphinx-admonition-mwe

Notice that `test-warning` is generated only once, and where it points is arbitrary. If I run `myst-inv` I get the following:
```yaml
name: Sphinx MWE
version: ''
base_url: http://localhost:8000
objects:
  std:
    label:
      genindex:
        loc: genindex.html
        text: Index
      modindex:
        loc: py-modindex.html
        text: Module Index
      py-modindex:
        loc: py-modindex.html
        text: Python Module Index
      search:
        loc: search.html
        text: Search Page
      test-warning:
        loc: other_page.html#test-warning
        text: null
    doc:
      index:
        loc: index.html
        text: Sphinx admonition MWE
      other_page:
        loc: other_page.html
        text: Another page
      referencing_page:
        loc: referencing_page.html
        text: Referencing page
```

Having only the content be included would minimize these unexpected effects.
