### ISSUE TITLE
Align table to center

### ISSUE THREAD

**Issue by eflanigan00** [sphinx-doc/sphinx#3942]
The tables pushed to the left looks bad. How can I canter the table.
This isn't working for me:

    .. table:: 
       :align: center

        === ===
          A   B
        === ===
         1   2
        === ===

docutils.__version__ is  '0.13.1'
sphinx.__version__ is '1.5.6'

**Comment by eflanigan00** [comment]
I also tried installing sphinx 1.6.3 with and docutils 0.14 with pip. Same result.

**Comment by eflanigan00** [comment]
Anyone have any ideas on this? Seems like a fundamental function.

**Comment by tk0miya** [comment]
What output format did you use? HTML? LaTeX? others?
I'll take a look.

**Comment by eflanigan00** [comment]
html

**Comment by jfbu** [comment]
the html tag ``<table border="1" class="docutils align-center">`` is generated like when using directly Docutils. But the alabaster, classic, readthedocs, agogo themes do not style it in my brief testing. When trying with Docutils ``rst2html.py`` one sees that the html file contains in its ``<head>`` some inline css spec

```css
table.align-center {
    margin-left: auto;
    margin-right: auto;
}
```

but the above mentioned themes style (I checked agogo and alabaster and readthedocs) use only

```css
.align-center {
    text-align: center;
}
```

readthedocs has something like

```css
.rst-content .align-center {
    margin: auto;
        margin-bottom: auto;
    display: block;
}
```


Note: your mwe has wrong indentation causing failed Sphinx html build. I corrected it for my testing.

Thus this appears as deficient CSS styling in html themes (possibly on purpose).

With the `alabaster` theme I fixed it by creating a `custom.css` file in `_static/` of the source repertory (assuming ``html_static_path = ['_static']``) and with contents

```css
table.align-center {
    margin-left: auto;
    margin-right: auto;
}
```
