### ISSUE TITLE
Additional vertical spacing in sphinxVerbatim environment (latex output)

### ISSUE THREAD

**Issue by skirpichev** [sphinx-doc/sphinx#6733]
In the [diofant docs](https://github.com/diofant/diofant/tree/master/docs) I use xelatex engine and following preamble:
```latex
\setmainfont{DejaVu Serif}
\setsansfont{DejaVu Sans}
\setmonofont{DejaVu Sans Mono}
```

HTML output from the sphinx looks fine (see e.g. [this](https://diofant.readthedocs.io/en/v0.10.0/tutorial/intro.html), an example of ``solve()`` usage) after slight css adaptation
```css
.rst-content div[class^="highlight"] pre {
    line-height: normal;
    font-family: 'DejaVu Sans Mono', 'DejaVuSansMonoBook', 'DejaVuSansMonoBookFallback', monospace;
}
```

But in the PDF output there are additional vertical spacing (like one, removed by line-height directive in the HTML output).  See screenshot from the project issue https://github.com/diofant/diofant/issues/754.
