### ISSUE TITLE
 Safari doctests selections doesn't work 

### ISSUE THREAD

**Issue by V0lantis** [sphinx-doc/sphinx#9098]
**Describe the bug**
The doctest selection isn't working properly on Safari, see below : 
On Chrome : 
![Capture d’écran 2021-04-10 à 16 59 58](https://user-images.githubusercontent.com/37664438/114274508-f381d280-9a1e-11eb-8d49-77effd97ec95.png)

On Safari : 
![Capture d’écran 2021-04-10 à 17 04 35](https://user-images.githubusercontent.com/37664438/114274504-f086e200-9a1e-11eb-923d-4fa19dc8d45d.png)

This is because of https://stackoverflow.com/questions/34372056/how-to-make-user-select-work-for-safari-browser/34372191#34372191

I believe the issue lay in `./sphinx/themes/basic/static/basic.css_t:774: ` : 
```css
table.highlighttable td.linenos,
span.linenos,
div.doctest > div.highlight span.gp {  /* gp: Generic.Prompt */
    user-select: none;
}
```

To revole the issue, it should be : 

```css
table.highlighttable td.linenos,
 span.linenos,
 div.doctest > div.highlight span.gp {  /* gp: Generic.Prompt */
   user-select: none;
   -webkit-user-select: text; /* Safari fallback only */
   -webkit-user-select: none; /* Chrome/Safari */
   -moz-user-select: none; /* Firefox */
   -ms-user-select: none; /* IE10+ */
 }
```

**To Reproduce**
Just go to http://scipy.github.io/devdocs/tutorial/linalg.html#numpy-matrix-vs-2-d-numpy-ndarray 
with safari and try to select the doc code. We shouldn't be selecting the `>>>` as in Chrome

I try to resolved it myself to make a PR, but I wasn't able to reproduce the behavior on the generated doc.
